version: '3.1'

services:
    db:
      image: postgres
      restart: always
      env_file:
        - .env
      ports:
        - "5432:5432"
    redis:
      image: redis
    server:
      build: .
      restart: always
      env_file:
        - .env
      ports:
        - "9999:8000"
      depends_on:
        - db
        - redis
      volumes:
        - .:/app
    celery:
      build:
          context: .
      env_file:
        - .env
      volumes:
        - ./utils:/app/utils 
      container_name: celery_app
      command: ["/app/celery.sh", "celery"]
      depends_on:
        - redis
    celery-beat:
      build:
          context: .
      env_file:
        - .env
      volumes:
        - ./utils:/app/utils 
      container_name: celery-beat
      command: ["/app/celery.sh", "beat"]
      depends_on:
        - redis
    flower:
      build:
        context: .
      env_file:
        - .env
      container_name: flower_app
      command: ["/app/celery.sh", "flower"]
      depends_on:
        - redis
        - celery
      ports:
        - 8888:5555